//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.order_product = new HashSet<order_product>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int point_id { get; set; }
        public int status_id { get; set; }
        public int take_code { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime delivery_date { get; set; }
    
        public virtual pickup_point pickup_point { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_product> order_product { get; set; }
        public virtual status status { get; set; }
        public virtual user user { get; set; }
    }
}
